let items=[
    {
        id:'01',
        Compname:"adiddas",
        Productname:"Cartoon Astronout Tshirt",
        productdetails:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio veniam mollitia quibusdam temporibus porro voluptatibus nisi nostrum ab repellendus ullam.",
        ratings:"4",
        price:"78",
        image:"/img/products/f1.jpg",
    },
    {
        id:'02',
        Compname:"adiddas",
        Productname:"Cartoon tommy Tshirt",
        productdetails:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio veniam mollitia quibusdam temporibus porro voluptatibus nisi nostrum ab repellendus ullam.",
        ratings:"4",
        price:"80",
        image:"/img/products/f2.jpg",
    },
    {
        id:'03',
        Compname:"adiddas",
        Productname:"Cartoon Astronout Tshirt",
        productdetails:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio veniam mollitia quibusdam temporibus porro voluptatibus nisi nostrum ab repellendus ullam.",
        ratings:"4",
        price:"90",
        image:"/img/products/f3.jpg",
    },
    {
        id:'04',
        Compname:"adiddas",
        Productname:"Cartoon Astronout Tshirt",
        productdetails:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio veniam mollitia quibusdam temporibus porro voluptatibus nisi nostrum ab repellendus ullam.",
        ratings:"4",
        price:"78",
        image:"/img/products/f4.jpg",
    },
    {
        id:'05',
        Compname:"adiddas",
        Productname:"Cartoon Astronout Tshirt",
        productdetails:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio veniam mollitia quibusdam temporibus porro voluptatibus nisi nostrum ab repellendus ullam.",
        ratings:"4",
        price:"78",
        image:"/img/products/f5.jpg",
    },
    {
        id:'06',
        Compname:"adiddas",
        Productname:"Cartoon Astronout Tshirt",
        productdetails:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio veniam mollitia quibusdam temporibus porro voluptatibus nisi nostrum ab repellendus ullam.",
        ratings:"4",
        price:"78",
        image:"/img/products/f6.jpg",
    },
    {
        id:'07',
        Compname:"adiddas",
        Productname:"Cartoon Astronout Tshirt",
        productdetails:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio veniam mollitia quibusdam temporibus porro voluptatibus nisi nostrum ab repellendus ullam.",
        ratings:"4",
        price:"78",
        image:"/img/products/f7.jpg",
    },
    {
        id:'08',
        Compname:"adiddas",
        Productname:"Cartoon Astronout Tshirt",
        productdetails:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Odio veniam mollitia quibusdam temporibus porro voluptatibus nisi nostrum ab repellendus ullam.",
        ratings:"4",
        price:"78",
        image:"/img/products/f8.jpg",
    }
]